cloudwatch.go, main.go
This allows filtering by queue, along with some substantial refactoring.
=> Add a -queue flag to allow filtering metrics by queue

main.go
This increases the page size for requests to the API from the default of 25 to 100. This should hopefully decrease the assault on the BK api. /cc @toolmantim
=> Increase page size

README.md, lambda.go
=> Add BUILDKITE_QUIET support to lambda

collector/collector.go
=> Add a 5 second timeout for metrics requests

README.md
Update capitalization  on Datadog
=> Update capitalization  on Datadog

README.md
=> Update readme to reflect elastic stack's changed paths

backend/backends.go, backend/cloudwatch.go, backend/prometheus.go, backend/prometheus_test.go, backend/statsd.go, lambda.go, vendor/vendor.json
Replace all references to github.com/buildkite/buildkite-metrics with github.com/buildkite/buildkite-agent-metrics
=> Update references to  github.com/buildkite/buildkite-metrics

.buildkite/pipeline.release.yml, .buildkite/pipeline.yml, .buildkite/steps/build-lambda.sh, .buildkite/steps/upload-to-s3.sh
Move to the standard buildkite lamba bucket vs `buildkite-metrics`.
=> Upload lambda for every build

README.md
=> Clarify lambda handler in README, add example

collector/collector.go
I neglected to add the new org detection to the per-queue metrics, which results in the following error:
```
InvalidParameter: 6 validation error(s) found.
- minimum field size of 1, PutMetricDataInput.MetricData[0].Dimensions[1].Value.
- minimum field size of 1, PutMetricDataInput.MetricData[1].Dimensions[1].Value.
- minimum field size of 1, PutMetricDataInput.MetricData[2].Dimensions[1].Value.
- minimum field size of 1, PutMetricDataInput.MetricData[3].Dimensions[1].Value.
- minimum field size of 1, PutMetricDataInput.MetricData[4].Dimensions[1].Value.
- minimum field size of 1, PutMetricDataInput.MetricData[5].Dimensions[1].Value.
: ErrInvalidParams
null
```
=> Add missing organization dimension to per-queue metrics

collector/collector.go
Correctly handle http errors and exit. 
Closes #75.
=> Handle http errors from the API

.buildkite/steps/upload-to-s3.sh
New: af-south-1, ap-east-1, eu-south-1, me-south-1
Related: https://github.com/buildkite/buildkite-agent-scaler/pull/33
=> Support more regions

README.md, go.mod, go.sum
I've done some ad-hoc testing of this but nothing serious.
=> Update README and a dependency

main.go
Fixes https://github.com/buildkite/buildkite-agent-metrics/issues/115.
=> Support getting agent token from BUILDKITE_AGENT_TOKEN env var

.buildkite/steps/release-github.sh, RELEASE.md
=> More fixes to the automated release

collector/collector.go
When collecting metrics for all queues a non `http.StatusOK` response from the API is correctly checked to ensure its content type is JSON before attempting to JSON decode it.
Unfortunately this same check was omitted from the code path that retrieves metrics when individual queues have been specified.
For example in the event of a 500 response ,which is returned as HTML, failing to check the response content type leads to the JSON decoder trying to decode HTML and the following error:
`invalid character '<' looking for beginning of value: SyntaxError` which isn't very useful to the user.
=> Handle API errors when querying queue

collector/collector.go
One if/else wrapping two huge branches? I don't think so.
=> Split Collect

lambda/main.go
=> Fix non-Secrets Manager token providers

main.go
=> Fix CloudWatch region defaulting

go.mod, go.sum
=> Bump Go to 1.23

backend/newrelic.go, go.mod, go.sum
=> Fix New Relic Go agent dep

.buildkite/pipeline.release.yml
Forgot to update the Compose service.
=> Fix GitHub release step

.buildkite/pipeline.release.yml
=> Remove step dependencies in release pipeline

.buildkite/pipeline.release.yml
=> Add ECR plugin

.github/CODEOWNERS, .github/dependabot.yml
Open to suggestions for exactly which owning team to use.
=> Update CODEOWNERS, dependabot.yml

CHANGELOG.md
=> Update v5.10.0 changelog

.buildkite/Dockerfile.lint, .buildkite/docker-compose.yaml, .buildkite/pipeline.yml, .buildkite/steps/check-code-committed.sh, .golangci.yml, backend/cloudwatch.go, backend/opentelemetry.go, backend/prometheus_test.go, collector/collector.go, collector/collector_test.go
=> golangci-lint
