- README.md
- main.go
We've got a bit of an issue with our ASG in EC2, its scaling policies are based on the buildkite-metrics cloudwatch data publisher. Scaling in is a bit of an issue though, because binding to ScheduledJobsCount can cause a downscale in the middle of a build, since there are no remaining ScheduledJobs. Binding on RunningJobsCount can cause the ASG to scale in before it can accept a job. It'd be nice to have a composite metric, say OpenJobsCount, which is comprised of RunningJobs and ScheduledJobs. Which is what I've added in this PR
> OpenJobsCount

- main.go
We are seeing intermittent failures to collect metrics. When failures happen, our logs are showing the following nil pointer dereference error:
```
2016/09/15 05:29:39 Collecting running and scheduled build and job metrics
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x408126]
goroutine 1 [running]:
panic(0x847ba0, 0xc8200100a0)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.listBuildsByOrg.func1(0x1, 0x0, 0x0, 0xc82005d500, 0x0, 0x0)
/go/src/github.com/buildkite/buildkite-metrics/main.go:402 +0x386
main.(*pager).Pages(0xc820024080, 0xc82004daa0, 0x0, 0x0)
/go/src/github.com/buildkite/buildkite-metrics/main.go:383 +0x3c
main.(*result).addBuildAndJobMetrics(0xc8200b4b00, 0xc8200125f0, 0x7fffdefa7d10, 0x3, 0x0, 0x7fffdefa7d4b, …
```
> Improve error logging

- main.go
This allows comma delimited queues to be passed in to the `--queue` filter for forthcoming elastic stack changes.
> Support multiple queues via --queue

- main.go
Reverts buildkite/buildkite-metrics#13
Sadly this has broken the latest metrics binary, so let's go back to a working version for now.
> Revert "Support multiple queues via --queue"

- main.go
HTTP debugging is now done with `--debug` and HTTP_TRACE=1
> Debug flag now shows useful debugging, added dry-run

- .buildkite/pipeline.yml
- Makefile
- cloudwatch.go
- collector/collector.go
- collector/collector_test.go
- docker-compose.yml
- lambda.go
- main.go
Turns out not having tests sucks, as does having loads of code in the main package. This remedies both of these things to a minimal extent.
> Moved collector into subpackage with tests

- collector/collector.go
- collector/collector_test.go
This replaces #21, wanted to prove the issue with tests before fixing it.
> Correctly filter stats by queue

- README.md
- lambda.go
The 1.3.0 release lambda function logged all queues, this adds support for `BUILDKITE_QUEUE` and also for logging output.
> Support the queue parameter and logs in lambda func

- .buildkite/pipeline.yml
- .buildkite/upload.sh
- .gitignore
- Makefile
Seems like lambda's need to be from a bucket in the same region, so this uploads to multiple regions.
> Upload lambda to region specific buckets

- lambda.go
I've noticed that we are seeing lots of connection errors in our lambdas. This adds some basic retry ability.
> Add retry for failed bk calls to lambda

- backend/statsd.go
- vendor/github.com/DataDog/datadog-go/statsd/README.md
- vendor/github.com/DataDog/datadog-go/statsd/statsd.go
- vendor/github.com/DataDog/datadog-go/statsd/udp.go
- vendor/github.com/DataDog/datadog-go/statsd/uds.go
- vendor/vendor.json
This PR updates StatsD client library and flushes statsd commands at the end of `Collect` call to fix #37 This is something that happened to us while using the statsd backend without the `-interval` parameter.
I've tested the resulting binary with and without `-interval` to check that don't change its behaviour.
> Ensure statsd commands are flushed after each run

- backend/prometheus.go
There is currently a bug where if queues fail to report to the metrics collector the last known value for that queue will persist forever.
This can happen when an instance dies or is killed ungracefully, and causes incorrect metrics to be reported.
Feel free to close this if there is a more elegant solution but it is important for our use case that this bug is fixed and the metrics are correctly reported. #42
> Reset prometheus queue gauges to prevent stale values persisting

- README.md
- backend/cloudwatch.go
- backend/cloudwatch_test.go
- lambda.go
- main.go
This allows a custom dimension to be added to Cloudwatch metrics, for instance `TeamName`, or `StackName` or `AccountID`. 
Related to https://github.com/buildkite/elastic-ci-stack-for-aws/issues/452.
> Allow a custom cloudwatch dimension flag

- backend/cloudwatch.go
- collector/collector.go
We've added the org slug to at the agent metrics json response, so this takes that slug and uses it as an extra Cloudwatch dimension. 
This should be a non-breaking change.
> Expose org slug as a cloudwatch dimension

- backend/cloudwatch.go
Ugh, I've misunderstood how Cloudwatch metrics work. All dimensions submitted must be matched on, so we can't submit a data point with a Org and a Queue dimension and then only match on the Queue dimension. 
This adds two data points, one with the Queue dimension and the other with Queue+Org. 
Without this change, the Elastic Stack would have to add back the OrgSlug as a mandatory param.
> Add additional metrics with only Queue dimension

- backend/ssm.go
- lambda/main.go
ssm support extracted from https://github.com/buildkite/buildkite-agent-metrics/pull/59
> add support for buildkite token from ssm

- collector/collector.go
- collector/collector_test.go
- lambda/main.go
- main.go
The Buildkite Agent Metrics API returns a header `Buildkite-Agent-Metrics-Poll-Duration` that indicates the minimum poll duration. This is generally 10s, but under periods of heavy load it can scale up.
This limit is enforced in the cli tool and also in the lambda via global state.
> Enforce Buildkite-Agent-Metrics-Poll-Duration header

- Dockerfile
- README.md
Related to #51, I added a base `Dockerfile` to create a local image for the `buildkite-agent-metrics`.
> feat: added dockerfile

- backend/cloudwatch.go
- lambda/main.go
- main.go
Metrics don't use a particular region, so this adds a default. 
Closes #44.
> Read AWS_REGION for cloudwatch, default to us-east-1

- collector/collector.go
This adds support for a new metric we've exposed `WaitingJobsCount`. This is jobs that are waiting behind a `wait` step, which will enable pre-emptive scaling.
> Add WaitingJobsCount metric

- README.md
- backend/cloudwatch.go
In 5.0, we will remove metrics with just a Queue dimension in favour of a default of Queue, Org.
> Drop metrics with only queue dimension

- collector/collector.go
- collector/collector_test.go
thanks for merging my previous PR.
I would like to suggest this change to add `BusyAgentPercentage` metric, similar to `BusyAgentCount` but reported as the % of agents being busy at the moment.
We have been using this metric for a while in our fork to enable TargetTrackingScaling and it's working very well, it may be useful for someone else.
see https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html
> Add BusyAgentPercentage metric

- README.md
- backend/backends.go
- backend/newrelic.go
- backend/newrelic_test.go
- go.mod
- go.sum
- lambda/main.go
- main.go
Adds [New Relic Insights](https://newrelic.com/products/insights) monitoring integration to `buildkite-agent-metrics`. I discovered NR does not accept custom Cloudwatch metrics out of the box so this change was born out of a need to write glue code to forward these metrics to New Relic. This work has been tested and is functional in Culture Amp's continuous integration environment as a Lambda using AWS SAM to deploy and manage it. Further rationale for why this might be considered is that New Relic's [`go-agent`](https://github.com/newrelic/go-agent) is, mercifully, a standalone dependency. 🎉 
- Added `backend/newrelic.go` driver to support publishing New Relic custom events
- Brief tests; admittedly this doesn't have great code cov as I didn't really want to invoke mocking libraries for …
> Add New Relic backend

- README.md
- collector/collector.go
- collector/collector_test.go
- lambda/main.go
- main.go
This adds support for multiple queues:
```bash
buildkite-agent-metrics -token abc123 -interval 30s -queue my-queue1 -queue my-queue2
```
> Support multiple queue params

- backend/cloudwatch.go
- backend/ssm.go
- backend/stackdriver.go
The current buildkite-agent-metrics daemon can only collect and export data for a single organization. 
Users who use multiple Buildkite organizations within a single Google Cloud project (e.g. bazel and bazel-testing) have to launch multiple instances of the daemon, each with the organization-specific agent token.
However, because the daemon didn't take the organization name into account when generating the metrics name, the daemons would try to write into each others Stackdriver metrics, causing API errors due to too frequent updates and data from multiple orgs being mixed.
It seems like a nice way to solve this is to use the organization name as part of the metric name.
> stackdriver: Use organization specific metric names.

- README.md
- lambda/main.go
To allow the metrics lambda to support monitoring multiple queues, we can perform a string split by comma if it is not-empty. `strings.Split` preserves expected functionality of a single queue if there are no commas:
```sh
gore> :import "strings"
gore> strings.Split("one-queue", ",")
[]string{"one-queue"}
gore> strings.Split("first-queue,second-queue", ",")
[]string{"first-queue", "second-queue"}
```
> Allow lambda BUILDKITE_QUEUE envvar to be a comma separated list

- collector/collector.go
- main.go
I'm using the agent metrics with `docker`, and I notice an unusual number of restarts of the container on our Kubernetes:
```NAME                                 READY   STATUS    RESTARTS   AGE
buildkite-metrics-66cf555bfc-xn668   1/1     Running   55         37d
```
Looking over the logs, I saw that whenever there's a fail of communication, the container restarts, because of the `os.Exit(1)` on the main:
```
2019/09/17 10:26:49 Collecting agent metrics for all queues
Get https://agent.buildkite.com/v3/metrics: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
exit status 1
```
My proposal is to not exit when there's a error on the `Collect`, just log the error, so we can have the agent running without exiting:
```
2019/09/17 …
```
> feat: don't exit on collect errors

- lambda/main.go
the logic is revered in the code, when `jsonKey` is empty it tries to use it, which results in
```
The token you provided "
{
"token": "<REDACTED>"
}
" is not a valid organization agent registration token: errorString
```
> fix reversed comparison

- .buildkite/pipeline.release.yml
- .buildkite/steps/release-github.sh
The agents processing the `deploy` queue have changed to an elastic stack.
They have the tools required (awscli, docker) and the required IAM permissions (uploading to S3), but we need to read the github API from SSM ourselves.
One of the steps also uses `github-release`, which isn't available on the elastic stack. I've switched from manually running a docker container with the binary, to running the entire step in a container that has it. This is mainly for consistency with other pipelines that use `github-release`.
> update release-related steps to work on the new deploy queue

- go.mod
To specify the Golang version in the `go.mod` file.
Building the `lambda` package using `go >= 1.14` breaks.
```
go: inconsistent vendoring in /Users/alloveras/go/src/github.com/alloveras/buildkite-agent-metrics:
cloud.google.com/go@v0.37.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/DataDog/datadog-go@v0.0.0-20180822151419-281ae9f2d895: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/aws/aws-lambda-go@v1.6.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/aws/aws-sdk-go@v1.15.66: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/golang/mock@v1.2.0: is explicitly required in go.mod, but not marked as …
```
> go.mod: Adds Golang version

- Dockerfile
Bumped on master in https://github.com/buildkite/buildkite-agent-metrics/commit/f83991c2bb8af7b3ac3a2cd6873e48f201b65599 and https://github.com/buildkite/buildkite-agent-metrics/commit/6ba4f87a877dce2a32e8bb5b5f6dc7665d40dcfe
> Build the docker image binary using golang 1.16 too

- CHANGELOG.md
- version/version.go
Merging this to master will make the final step in .buildkite/pipeline.yml notice the version number is not a tag and upload the release steps which will make one and attach the binaries.
> Release updates for 5.2.1

- collector/collector.go
The current implementation will use two different `http.Client` configurations depending on whether the collector is targetting ALL queues or only particular ones.
When targetting particular queues, the code will use `http.DefaultClient` and, as a consequence of its default values, it will use an infinite client timeout. This is particularly problematic as upstream servers may not have timeouts set either or use a very long one. Hence, when used in the Lambda environment, a bad behaving request can force the function execution time to skyrocket and go past the Lambda execution timeout.
To ensure that both configurations (all queues vs particular queues) do use the same HTTP client configurations with a sensible client timeout value.
> Standardize http.Client collector configurations

- .buildkite/pipeline.release.yml
- .buildkite/pipeline.yml
- .buildkite/steps/release-github.sh
Now that OIDC is available, we prefer to use it to assume specific IAM roles for deploy tasks.
For pushing to S3, assume an IAM role from the account where the S3 buckets live.
For releasing to GitHub, assume role in the account running the step and use that to set an ENV var from SSM Parameter Store
> Update release process to use OIDC

- .buildkite/pipeline.release.yml
In #133 we updated the relase steps to use OIDC for assuming roles as needed. The release to s3 steps worked as planned, however the release to GitHub step needs some tweaks:
1. fix the SSM parameter store path
2. explictly pass the environment variable into the docker container
> Fix GitHub release now that we're using OIDC

- .github/dependabot.yml
We recently (#131) did a bulk update to many go modules, fixing various security issues.
This configures dependabot to open PRs with occasional version bumps. We don't want to wake up to 100 PRs each Monday though, so only allow two PRs at a time. In a small project like this, a couple of bumps per week should be plenty. Maybe we could even tune it down further. 2 per month?
> Allow dependabot to slowly keep gomod up to date

- .buildkite/steps/release-github.sh
Once an updated version is available in the alpine repos, we can
uncomment this.
> Fix `--verify-tag` not available in github-cli 2.20

- README.md
> add notes about what the job states mean

- collector/collector.go
- lambda/main.go
- main.go
By default, the http `timeout` is set to 15 seconds, which is mostly fine. However, if folks are seeing timeouts occur it might be nice if we let them adjust the timeout on the http calls so that they can test prior to raising an issue. This change ensures that the default remains at 15 seconds, which may or may not have been picked for a reason, where someone doesn't opt to set it, but gives the option to do so. It also doesn't create a global increase of timeouts.
> Make the timeout configurable

- collector/collector.go
- main.go
When an invalid token is used for invoking `buildkite-agent-metrics` as a daemon - unauthorized errors are indefinitely output, ideally the process exits at some point to signal that it has encountered an error so the calling process can restart it with the correct token.
@triarius - unsure on where you prefer the process exit, PTAL.
Resolves #200
> feat(collector): exit on 401 response

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.7.0...v5.8.0)
- Exit with code 4 on 401 response from the API [#203](https://github.com/buildkite/buildkite-agent-metrics/pull/203) (@NotArpit)
- Bump github.com/aws/aws-sdk-go to 1.45.6 [#191](https://github.com/buildkite/buildkite-agent-metrics/pull/191) [#194](https://github.com/buildkite/buildkite-agent-metrics/pull/194) [#195](https://github.com/buildkite/buildkite-agent-metrics/pull/195) [#197](https://github.com/buildkite/buildkite-agent-metrics/pull/197) [#198](https://github.com/buildkite/buildkite-agent-metrics/pull/198) [#199](https://github.com/buildkite/buildkite-agent-metrics/pull/199) [#201](https://github.com/buildkite/buildkite-agent-metrics/pull/201) (@dependabot[bot])
- Bump …
> Bump version and CHANGELOG for v5.8.0

- main.go
There is no functionality that supports population of `gcpProjectId` and `queues` via environment variables. This limits our ability to run this where config is dynamically populated and `gcpProjectId`/`queues` attributes are a concern of the execution environment and not coupled to binary invocation.
Use `GCP_PROJECT_ID` and `BUILDKITE_QUEUE` environment variables to populate config. 
- If `gcpProjectID` is an empty string we fall back to the environment variable `GCP_PROJECT_ID`.
- If `queues` aren't specified (i.e. `len(queues) == 0`) we fall back to `BUILDKITE_QUEUE` (same as AWS lambda) environment variables.
These changes are backwards compatible to existing usage of this binary. Happy to discuss implementation details if maintainers feel otherwise :)
@triarius @DrJosh9000  PTAL.
> feat(gcp): add env vars for buildkite queues and gcp project id

- collector/collector.go
In https://github.com/buildkite/buildkite-agent-metrics/pull/203 in `//collector/collector.go` we used error wrapping to exit with code 4 on a 401 response from the agent metrics API. However this was only done in the conditional branch when no queues are specified (i.e. ingest metrics for all queues). Hence when specifying a queue via `-queue` CLI flag, we do not get the exit on status code 401.
Exit on 401 response in the conditional branch where `len(c.Queues) != 0` for parity with `len(c.Queues) == 0`.
@triarius @DrJosh9000 PTAL.
> fix(collector): exit on 401 when queues specified

- .buildkite/pipeline.release.yml
- .buildkite/pipeline.yml
- .buildkite/steps/build-binary.sh
- .buildkite/steps/build-lambda.sh
- Dockerfile
- Dockerfile.lambda
- README.md
- lambda/main.go
I also cleaned up some deprecated code. I tried to use the `static: true` option to the cross compile plugin, but it uses some outdated options to `go build` that did not work on non-linux OSes. So I changed the build step to use the docker plugin and a wrote a script to build and upload the artifact instead.
Fixes: #202
> Change build process to better support `provided.al2`

- README.md
One more reference to go1.x runtime was remaining in the readme. This fixes that up
> Fix another reference to go1.x

- .buildkite/pipeline.yml
- README.md
- backend/cloudwatch.go
- backend/newrelic.go
- backend/newrelic_test.go
- backend/prometheus.go
- backend/prometheus_test.go
- backend/stackdriver.go
- backend/stackdriver_test.go
- backend/statsd.go
- collector/collector.go
- collector/collector_test.go
- go.mod
- go.sum
- lambda/main.go
- main.go
There's a lot going on here, which I don't like doing, but I tried to keep the various commits separate.
Arguably we should have a single API token that does a single request (like GraphQL), but... not today.
Since this is a loop that produces multiple results, the cluster name from the response occupies a new field in the collector result. One wrinkle is `minPollTime`; I've chosen to use the maximum from the responses.
Cluster neatly fits as a label / dimension / tag, where supported. I'm not sure whether Cloudwatch or StatsD are correct since the tests are sparse / non existent. Also, the StatsD backend must work with and without tag support, so (after splitting the method) I copied what the existing code did to distinguish queue metrics from totals.
Assuming it all works, I think the …
> Collect from multiple clusters

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.8.0...v5.9.0)
> [!WARNING]
> This release adds a new Cluster label/tag/dimension, which is populated when using agent cluster tokens. This may break continuity with existing time series!
- Collect from multiple clusters [#227](https://github.com/buildkite/buildkite-agent-metrics/pull/227) (@DrJosh9000)
- feat(gcp): add env vars for buildkite queues and gcp project id [#212](https://github.com/buildkite/buildkite-agent-metrics/pull/212) (@NotArpit)
- Change build process to better support `provided.al2` [#225](https://github.com/buildkite/buildkite-agent-metrics/pull/225) (@triarius)
- fix(collector): exit on 401 when queues specified [#211](https://github.com/buildkite/buildkite-agent-metrics/pull/211) …
> Bump version and changelog for v5.9.0

- README.md
- lambda/main.go
https://github.com/buildkite/buildkite-agent-metrics/pull/227 added support for Clusters (@DrJosh9000), with agent registration tokens provided as a comma separated list.
The assumption for secrets manager secrets was that it would be a single secret with a comma separated list of values. This is not ideal, as it means a new secret needs to be created just for this lambda. If instead a comma separated list of secrets is used, we can keep the registration tokens in their own secrets which is referenced in multiple places.
This PR supports multiple secrets provided to `BUILDKITE_AGENT_SECRETS_MANAGER_SECRET_ID` (comma-seperated) and queries secrets manager for each value.
I've built the lambda zip locally and tested on AWS with 2 agent registration tokens across 2 clusters.
> Support for multiple secrets manager secrets 

- backend/cloudwatch.go
- backend/newrelic.go
- backend/prometheus.go
#227 added support for clusters, but as was somewhat anticipated, it
broke compatibility with some existing backends because it added a
new dimension/label/tag or some equivalent for the cluster. In this PR,
we refrain from doing so if the cluster is the empty string.
One thing to note is that the cluster is not specified when the process
starts, it is determined from the cluster token by the backend which includes the name
of the cluster in its response. If the token is for unclustered agents,
that part of the response will be the empty string.
> Ignore cluster if it is empty

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.0...v5.9.1)
- Support for multiple secrets manager secrets command seperated [#233](https://github.com/buildkite/buildkite-agent-metrics/pull/233) (@lucylura)
- Ignore Cluster label/dimension/tag for empty unclustered queues. This may fix continuity errors when clusters are not used [#234](https://github.com/buildkite/buildkite-agent-metrics/pull/234) (@triarius)
- Document SSM Parameters names may be comma separated [#235](https://github.com/buildkite/buildkite-agent-metrics/pull/235) (@triarius)
- build(deps): bump github.com/aws/aws-sdk-go from 1.47.3 to 1.48.3 [#232](https://github.com/buildkite/buildkite-agent-metrics/pull/232) (@dependabot[bot])
> Update CHANGELOG and version for v5.9.1

- lambda/main.go
For some reason, these were hard coded to be off. Now, they can be controlled with env vars.
For the non lambda mode, there are already command line arguments for these.
> Allow env vars to control debug logging for the lambda

- backend/backends.go
- backend/cloudwatch.go
- backend/newrelic.go
- backend/prometheus.go
- backend/prometheus_test.go
- backend/stackdriver.go
- backend/statsd.go
- go.mod
- lambda/main.go
- main.go
- token/secretsmanager_test.go
- token/ssm_test.go
> For module versions v2 and later, this value must end with the major version number, such as /v2.
> -- https://go.dev/doc/modules/gomod-ref
This is necessary for #247.
> Add v5 to module path

- CHANGELOG.md
- README.md
- version/version.go
This also updates the install instruction in the README to use the v5 module path. (Which won't work until a v5.x.x tag is pushed that also has the v5 module path.)
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.2...v5.9.3)
- Add v5 to module path [#248](https://github.com/buildkite/buildkite-agent-metrics/pull/248) (@DrJosh9000)
- build(deps): bump golang.org/x/crypto from 0.14.0 to 0.17.0 [#246](https://github.com/buildkite/buildkite-agent-metrics/pull/246) (@dependabot[bot])
- build(deps): bump cloud.google.com/go/monitoring from 1.16.3 to 1.17.0 [#245](https://github.com/buildkite/buildkite-agent-metrics/pull/245) (@dependabot[bot])
- build(deps): bump github.com/aws/aws-lambda-go from 1.41.0 to 1.42.0 …
> Bump changelog and version for v5.9.3

- collector/collector.go
We print the time when a request starts and a response is received, but this also includes any DNS resolution.
To help debug slow DNS issues this PR now prints the timings when it starts/stops.
Inspired by https://github.com/golang/go/issues/21906#issuecomment-332116942
Output:
```
dns start: 2024-05-03 17:25:37.519031 +1000 AEST m=+0.013530292
dns done: 2024-05-03 17:25:37.556161 +1000 AEST m=+0.050660126
connection start: 2024-05-03 17:25:37.556272 +1000 AEST m=+0.050770667
connection done: 2024-05-03 17:25:37.708357 +1000 AEST m=+0.202855251
TLS Handshake start: 2024-05-03 17:25:37.70846 +1000 AEST m=+0.202958042
TLS Handshake done: 2024-05-03 17:25:37.872324 +1000 AEST m=+0.366821292
wrote headers: 2024-05-03 17:25:37.872614 +1000 AEST m=+0.367111959
wrote request: 2024-05-03 …
```
> Log DNS resolution times when debug http is enabled

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.3...v5.9.4)
- Log DNS resolution times when debug http is enabled [#278](https://github.com/buildkite/buildkite-agent-metrics/pull/278) (@patrobinson)
- build(deps): bump golang.org/x/net from 0.20.0 to 0.23.0 [#275](https://github.com/buildkite/buildkite-agent-metrics/pull/275) (@dependabot[bot])
- build(deps): bump github.com/prometheus/client_golang from 1.17.0 to 1.19.0 [#269](https://github.com/buildkite/buildkite-agent-metrics/pull/269) (@dependabot[bot])
- build(deps): bump github.com/aws/aws-sdk-go from 1.51.1 to 1.51.21 [#274](https://github.com/buildkite/buildkite-agent-metrics/pull/274) (@dependabot[bot])
- build(deps): bump github.com/prometheus/client_model from 0.5.0 to 0.6.0 …
> Bump version to v5.9.4

- collector/collector.go
To debug sudden spiking delay while collecting and processing metrics, it was required to collect more metrics during the HTTP requests.
Also, we noticed that the agent token is exposed to the log when HTTP debug is enabled, which can be a security risk.
It adds more traces to the HTTP Client tracer for more detailed event timing. Also, it updates the request dump to redact the Authorisation header if it exists.
> Adding more debug traces for HTTP and enhance security

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.4...v5.9.5)
- Adding more debug traces for HTTP and enhance security [#283](https://github.com/buildkite/buildkite-agent-metrics/pull/283) (@CheeseStick)
- Fix CloudWatch region defaulting [#282](https://github.com/buildkite/buildkite-agent-metrics/pull/282) (@DrJosh9000)
- build(deps): bump cloud.google.com/go/monitoring from 1.17.0 to 1.19.0 [#280](https://github.com/buildkite/buildkite-agent-metrics/pull/280) (@dependabot[bot])
- build(deps): bump github.com/prometheus/client_model from 0.6.0 to 0.6.1 [#276](https://github.com/buildkite/buildkite-agent-metrics/pull/276) (@dependabot[bot])
> Bump version and changelog to v5.9.5

- collector/collector.go
- collector/collector_test.go
- lambda/main.go
- main.go
To ensure we get consistent connection reuse, pooling I have extracted the HTTP Client used by all collections. This client has been configured with a set of timeouts at both the client and transport level.
I have used the following post as a reference https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts
> This change will ensure a single HTTP client is created

- README.md
- collector/collector.go
- lambda/main.go
- lambda/main_test.go
- main.go
To provide customers with more options to tune for their situation this introduces a new option to reduce or disable connection reuse. In some cases disabling connection reuse may avoid read timeouts or pausing for connections a server, or CDN may deprioritize.
I have also updated the documentation for the expanded timeout option to highlight it is used for more than just request timeout.
Also disabled redirects, again to ensure the client completes the operation quickly. 
See https://github.com/golang/go/blob/master/src/net/http/transport.go#L44-L55 for more context on the defaults.
> This change enables configuration of http connection pooling

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.5...v5.9.6)
- This change enables configuration of http connection pooling [#286](https://github.com/buildkite/buildkite-agent-metrics/pull/286) (@wolfeidau)
- This change will ensure a single HTTP client is created [#285](https://github.com/buildkite/buildkite-agent-metrics/pull/285) (@wolfeidau)
> Bump version and changelog to v5.9.6

- backend/prometheus.go
If a customer is running unclustered agents and using the prometheus backend then the CLI will panic when building the metrics.
```
panic: inconsistent label cardinality: expected 1 label values but got 0 in []string(nil)
goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).WithLabelValues(...)
github.com/prometheus/client_golang@v1.19.0/prometheus/gauge.go:238
github.com/buildkite/buildkite-agent-metrics/v5/backend.(*Prometheus).Collect(0x14000144618, 0x140008187c0)
github.com/buildkite/buildkite-agent-metrics/v5/backend/prometheus.go:65 +0x8b0
main.main.func1()
github.com/buildkite/buildkite-agent-metrics/v5/main.go:182 +0xc4
main.main()
github.com/buildkite/buildkite-agent-metrics/v5/main.go:194 +0x1160
```
This change leaves the pruning of empty cluster …
> fix for prometheus backend panic'ing when using unclustered agents

- Dockerfile.lambda
Just update the lambda dockerfile to pin the container, and use the [2023 release of amazon linux](https://github.com/amazonlinux/amazon-linux-2023).
> Update the lambda dockerfile to use al2023

- CHANGELOG.md
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.6...v5.9.7)
- fix for prometheus backend panic'ing when using unclustered agents [#288](https://github.com/buildkite/buildkite-agent-metrics/pull/288) (@wolfeidau)
- Update the lambda dockerfile to use al2023 [#291](https://github.com/buildkite/buildkite-agent-metrics/pull/291) (@wolfeidau)
- Allow dependabot to keep our dockerfiles up to date [#289](https://github.com/buildkite/buildkite-agent-metrics/pull/289) (@wolfeidau)
> Bump version and changelog to v5.9.7

- backend/prometheus.go
- main.go
This has been reoved as it can't work for more than one cluster as gauges are scoped to all clusters, but the collect function is called once for each agent token. In summary this leads to gauges only being correct for the last agent, depending what metrics were returned when the cluster was polled as the result doesn't always include all keys. 😭 
Also trimmed the pipeline metrics as they aren't used, and ensured the logger included short file name as it is helpful.
Added some comments to ensure my assumptions are captured and avoid confusion in the future.
> fix to remove reset in prometheus backend

- backend/prometheus.go
Track which queues are present in the most recent Collect for each cluster, and delete them from the metrics when they are no longer there.
Possible fix for #304 
#296 removed some code that was well-intentioned, but heavy-handed, and didn't make sense in a setup monitoring more than one cluster (or a cluster and unclustered...) But then there was nothing to remove old queues, which is a potential memory issue (minor) and causes metrics for deleted queues to get stuck on the last value (confusing).
> Delete Prometheus labels for deleted queues

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.8...v5.9.9)
- Delete Prometheus labels for deleted queues [#305](https://github.com/buildkite/buildkite-agent-metrics/pull/305) (@DrJosh9000)
- provide clearer direction on boolean environment variables [#298](https://github.com/buildkite/buildkite-agent-metrics/pull/298) (@wolfeidau)
- build(deps): bump docker/library/golang from 1.23.0 to 1.23.1 [#306](https://github.com/buildkite/buildkite-agent-metrics/pull/306) (@dependabot[bot])
- build(deps): bump docker/library/alpine from 3.20.2 to 3.20.3 [#307](https://github.com/buildkite/buildkite-agent-metrics/pull/307) (@dependabot[bot])
- build(deps): bump docker/library/alpine from 3.20.1 to 3.20.2 [#303](https://github.com/buildkite/buildkite-agent-metrics/p …
> Bump version to v5.9.9

- collector/collector.go
- collector/collector_test.go
Make sure to add Proxy config in Transport.
See https://pkg.go.dev/net/http#DefaultTransport for reference
Fixes #319
> Fix regression with HTTP Client and Proxy environment variables

- Dockerfile
`GO111MODULE=on` has been the default for... a while now.
`GOARCH=arm64` gets in the way of building a usable image if you just want the current arch.
`GOOS=linux` is possibly still relevant. 🤔 
Other tweaks:
* `apk add --no-cache`
* Fix Docker complaint about matching case (`FROM` vs `as`)
> Don't hardcode linux/amd64 or GO111MODULE in Dockerfile

- backend/prometheus.go
- backend/prometheus_test.go
- collector/collector.go
Pre-register all metrics with Prometheus, and change which data structure is looped over so that metrics that are no longer present in the collector result (typically for queues that exist but might not have agents or jobs) are naturally reset to 0.
Fixes #304
> Fix stale Prometheus metrics

- .buildkite/Dockerfile
- .buildkite/Dockerfile.build
- .buildkite/Dockerfile.release
- .buildkite/Dockerfile.test
- .buildkite/docker-compose.yaml
- .buildkite/pipeline.release.yml
- .buildkite/pipeline.yml
- .buildkite/steps/build-binary.sh
- .buildkite/steps/build-lambda.sh
- .buildkite/steps/release-github.sh
- .buildkite/steps/upload-to-s3.sh
- .github/dependabot.yml
* Use the `docker-compose` plugin
* Dockerfiles, so all steps use dependabot-updated images pulled from the cache
* `artifact_paths` instead of copying the agent into the container
> Pipeline cleanups

- .buildkite/Dockerfile.public
- .buildkite/pipeline.release.yml
- .buildkite/pipeline.yml
- .buildkite/steps/release-docker.sh
- .buildkite/steps/release-github.sh
- .buildkite/steps/release-s3-version.sh
- .buildkite/steps/upload-release-steps.sh
- .buildkite/steps/upload-to-s3.sh
- Dockerfile
Also run the release pipeline in a separate BK pipeline.
Fixes #51
> Add Docker image release

- .buildkite/steps/upload-to-s3.sh
`metrics-artifacts-build` is only set by the release pipeline trigger.
> Fix S3 upload for non-tagged builds

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.10...v5.9.11)
This release exists in order to make the pipeline push a Docker image to the new
[public repository!](https://gallery.ecr.aws/buildkite/agent-metrics)
- Fix S3 upload for non-tagged builds [#340](https://github.com/buildkite/buildkite-agent-metrics/pull/340) (@DrJosh9000)
- Add Docker image release [#339](https://github.com/buildkite/buildkite-agent-metrics/pull/339) (@DrJosh9000)
> Bump version and changelog for v5.9.11

- .buildkite/steps/release-docker.sh
`--tag foo:bar` as a single arg is not a valid flag, but `--tag=foo:bar` is valid.
Small bit of manual testing this time:
```shell
bash-3.2$ parse_version() {
>   local v="$1"
>   IFS='.' read -r -a parts <<< "${v%-*}"
>
>   for idx in $(seq 1 ${#parts[*]}) ; do
>     sed -e 's/ /./g' <<< "${parts[@]:0:$idx}"
>   done
>
>   [[ "${v%-*}" == "${v}" ]] || echo "${v}"
> }
bash-3.2$ registry="public.ecr.aws/buildkite/agent-metrics"
bash-3.2$ version_tags=($(parse_version "5.9.11"))
bash-3.2$ docker build "${version_tags[@]/#/--tag=${registry}:v}" .
[+] Building 17.2s (13/13) FINISHED                                          docker:orbstack
...snip...
=> => writing image sha256:b5162648ecf2f901b463c852eab2acfc2dfb0acd0aad5e7b2e77bb28c0  0.0s
=> => naming to …
```
> Fix --tag flags generated from Bash array

- .buildkite/Dockerfile.public
`buildkite artifact` subcommands do not preserve file mode.
> chmod +x the binaries in Dockerfile

- .buildkite/steps/release-docker.sh
It's not super clear to me why we can't do the multi-platform image build *and* push to ECR all in a single command. It might be naive optimism, but it's worth a shot. I don't expect this to speed things up too much, but a simpler script will be easier to maintain over time.
I also removed the creation of a custom buildx builder. These jobs are running on elastic-runners, which already have a buildx builder that's capable of multi-platform builds.
> Simplify docker release script

- .buildkite/pipeline.release.yml
- .buildkite/pipeline.yml
- .buildkite/steps/upload-to-s3.sh
We recently moved the S3 buckets that host our public lambdas to a new AWS account, and the OIDC assumable IAM roles for publishing to the buckets moved with them.
The replacement buckets have the same name, so we don't need to change them. However the recreated buckets use BucketOwnerEnforced for ownership and resource policies for access, instead of ACLs. We need to remove `--acl` from the upload command.
We also took the opportunity to setup S3 bucket replication, so we only need to push to the us-east-1 bucket now. S3 replication will handle copying to all the regional buckets.
> Update release process to assume new IAM roles via OIDC

- .github/dependabot.yml
Reduce distinct PRs for bumping container images. They all tend to bump simultaneously.
> Group container image bumps into single PR

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.11...v5.9.12)
- Update release process to assume new IAM roles via OIDC [#352](https://github.com/buildkite/buildkite-agent-metrics/pull/352) (@yob)
- Simplify docker release script [#347](https://github.com/buildkite/buildkite-agent-metrics/pull/347) (@yob)
- Group container image bumps into single PR [#356](https://github.com/buildkite/buildkite-agent-metrics/pull/356) (@DrJosh9000)
- build(deps): bump golang.org/x/crypto from 0.28.0 to 0.31.0 [#358](https://github.com/buildkite/buildkite-agent-metrics/pull/358) (@dependabot[bot])
- build(deps): bump google.golang.org/protobuf from 1.35.2 to 1.36.0 [#357](https://github.com/buildkite/buildkite-agent-metrics/pull/357) (@dependabot[bot])
- build(deps): bump …
> Bump version and changelog for v5.9.12

- README.md
- lambda/main.go
- main.go
This change will enable customers to override the endpoint flag via an **optional** environment variable.
> Add an environment variable to override the agent endpoint URL

- README.md
added a few lines in the README file explaining what some of the metrics do.
> Added detailed explanations about some metrics

- .github/CODEOWNERS
Adding CODEOWNERS file with Support Engineers as codeowners.
> Create CODEOWNERS - adding Support Engineers as CODEOWNERS

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.9.13...v5.10.0)
- Adding support for OpenTelemetry backend [#412](https://github.com/buildkite/buildkite-agent-metrics/pull/412) (@huewood)
- Added detailed explanations about some metrics [#364](https://github.com/buildkite/buildkite-agent-metrics/pull/364) (@amnabk)
- Clarify "running" and "unfinished" states in README [#355](https://github.com/buildkite/buildkite-agent-metrics/pull/355) (@ivannalisetska)
- Update CODEOWNERS, dependabot.yml [#389](https://github.com/buildkite/buildkite-agent-metrics/pull/389) (@DrJosh9000)
- Update CODEOWNERS [#380](https://github.com/buildkite/buildkite-agent-metrics/pull/380) (@karensawrey)
- Create CODEOWNERS - adding Support Engineers as CODEOWNERS …
> Bump version and changelog for v5.10.0

- README.md
- backend/opentelemetry.go
- lambda/main.go
- main.go
https://github.com/buildkite/buildkite-agent-metrics/pull/412 (by @huewood) kindly added a OpenTelemetry backend. Thanks @huewood 💚 
This PR makes the code a bit simpler by delegating to the built-in (and documented) mechanism on the OpenTelemetry SDK.
See comment on PR: https://github.com/buildkite/buildkite-agent-metrics/pull/412/files#r2174197744
> this header pattern of API keys is a bit of a HyperDX specific behavior, where the "standard" OTel collector expects either Authorization: Bearer <token> or Authorization: Basic <base64 user:password).
>
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/bearertokenauthextension/README.md
>
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/basicauthextension/README.md …
> Simplify OpenTelemetry backend

- .buildkite/pipeline.release.yml
Roll out using session tags for OIDC assumable IAM role trust policy. 
Follow on from the work to support session tags in https://github.com/buildkite-plugins/aws-assume-role-with-web-identity-buildkite-plugin/pull/18
Requires matching update to the IAM role in PR: https://github.com/buildkite/aws-buildkite-dev/pull/474
This is only changing the one pipeline, which uses an IAM role in `buildkite-dev` account. Additional pipelines defined in this repo will be updated when I move on to working on the `ops` repo roles.
> Update to use OIDC session tokens on AWS role assumption in buildkite-dev

- dashboards/grafana-prometheus.json
Add the JSON export of a Grafana dashboard that I whipped up. It is built assuming Grafana is being used with a Prometheus backend that scrapes buildkite-agent-metrics.
> Add Grafana dashboard (for use with Prometheus backend)

- backend/stackdriver.go
- collector/collector.go
- main.go
- token/secretsmanager.go
- token/ssm.go
In https://github.com/buildkite/buildkite-agent-metrics/issues/447, @trfullhart-benchling reported that HTTP 401 responses don't report the message that buildkite returns back with the response body.
This PR fixes that, and generally makes the HTTP error handling a little more consistent and reasonable. It also replaces a bunch of `fmt.Errorf("... %v")` with `fmt.Errorf("... %w")`, which will properly wrap errors as they should be wrapped.
Closes #447
> Better HTTP errors

- CHANGELOG.md
- version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-metrics/compare/v5.10.0...v5.11.0)
- Add Grafana dashboard (for use with Prometheus backend) [#436](https://github.com/buildkite/buildkite-agent-metrics/pull/436) (@DrJosh9000)
- Better HTTP errors, especially for HTTP 401 errors [#453](https://github.com/buildkite/buildkite-agent-metrics/pull/453) (@moskyb)
- Add lint step to pipeline [#454](https://github.com/buildkite/buildkite-agent-metrics/pull/454) (@moskyb)
- Update README with info about exisitng containers and Lambda [#431](https://github.com/buildkite/buildkite-agent-metrics/pull/431) (@DrJosh9000)
- Update to use OIDC session tokens on AWS role assumption [#424](https://github.com/buildkite/buildkite-agent-metrics/pull/424) (@duckalini)
- Update to use OIDC session …
> Bump version + changelog for v5.11.0
